[project]
name = "rm-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "transformers>=4.48.3",
    "trl>=0.14.0",
]
